name: Sadhan Deploy WorkFlow
on:
  push:
    branches: [master]
      
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [19.8.1]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3 # was "v2" before 
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # was "v2" before
        with: 
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: |
          npm install --legacy-peer-deps
          npm test
        env: 
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CALLBACK_URL: http://localhost:5000/google/callback
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 19.8.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - name: Build
        run: npm run build

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
  
