
name: Sadhan Deploy WorkFlow

on:
  push:
    branches: [master]

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19.8.1
    - name: npm install
      run: npm install
    # Heavily modified deploy job to fit render.com
    deploy:
    name: Deploy
      #needs: [test] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings


   
   
