
name: Sadhan Deploy WorkFlow

on:
  push:
    branches: [master]

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.8.1
        uses: actions/setup-node@v2
        with:
          node-version: 19.8.1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        # Heavily modified deploy job to fit render.com
    deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest

      steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings


   
   
